import os
import sys
import pymongo
import pandas as pd
from networksecurity.exceptions.custom_exception import NetworkSecurityException
from networksecurity.logging.logger import logger
from networksecurity.pipelines.training_pipeline import TrainingPipeline
from networksecurity.utils.common import load_object
from networksecurity.constants.model_trainer import FINAL_MODEL_PATH

from fastapi.middleware.cors import CORSMiddleware
from fastapi import FastAPI, UploadFile, Request, File
from uvicorn import run as app_run
from fastapi.responses import Response
from fastapi.responses import RedirectResponse
from fastapi.templating import Jinja2Templates


import certifi
ca = certifi.where()

templates = Jinja2Templates(directory="./templates")

# create the FastAPI application
app = FastAPI()

# allow requests from all origins (frontend applications) by using *
origins = ["*"]

# add CORS middleware
# CORS controls which websites are allowed to call this API
app.add_middleware(
    CORSMiddleware, 
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],    # allow GET, POST, PUT, DELETE, etc.
    allow_headers=["*"]     # allow all request headers
)

@app.get("/", tags=["authentication"])
async def index():
    # redirect user to FastAPI's autogenerated documentation "docs"
    # This documenation is where we see the fast api's UI
    return RedirectResponse(url="/docs", status_code=302)

@app.get("/train")
async def train_route():
    try:
        training_pipeline = TrainingPipeline()
        training_pipeline.initiate_training()
        return Response("Wonderful, the training is completed!")
    except Exception as e:
        raise NetworkSecurityException(e, sys)
    
@app.post('/predict')
async def predict_route(request:Request, file:UploadFile=File(...)): # UplaodFIle will allow to upload files in website
    try:
        # read data from file
        data = pd.read_csv(file.file)

        # load model AND DO PREDICTION
        network_classifier = load_object(FINAL_MODEL_PATH)
        y_pred = network_classifier.predict(data)
        data['prediction'] = y_pred     # add prediction to dataframe

        # convert dataframe to table for fast api website
        table_html = data.to_html(classes='table, table-striped')
        return templates.TemplateResponse("table.html", {"request":request, "table":table_html})

    except Exception as e:
        raise NetworkSecurityException(e, sys)
if __name__ == "__main__":
    app_run(app, host="0.0.0.0", port=8000)