COLLECTION_NAME = "NetworkData"
DATABASE_NAME = "AryanSavant"
ROOT_DIR = "1_data_ingestion"
INGESTED_DIR = "ingested"
RAW_DATA_FILE_NAME = "phisingData.csv"
FEATURE_STORE_DIR = "feature_store"
TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"